analytics_db: /my/custom/path/to/analytics
streamers:
  streamer_b: !Preset small
  streamer_a: !Specific
    strategy: !detailed
      high_odds:
        # bets placed outside this range
      - low_threshold: 10.0
        high_threshold: 90.0
        high_odds_attempt_rate: 1.0
        high_odds_points:
          max_value: 1000
          percent: 1.0
        # bets placed outside this range
      - low_threshold: 30.0
        high_threshold: 70.0
        high_odds_attempt_rate: 3.0
        high_odds_points:
          max_value: 5000
          percent: 5.0
      default:
        # bets placed within this range
        max_percentage: 55.0
        min_percentage: 45.0
        points:
          max_value: 100000
          percent: 25.0
    filters:
    - !DelayPercentage 50.0
presets:
  small:
    strategy: !detailed
      high_odds: null
      default:
        max_percentage: 0.0
        min_percentage: 0.0
        points:
          max_value: 0
          percent: 0.0
    filters:
    - !TotalUsers 300
    - !DelaySeconds 30
