streamers:
  example_streamer:
    strategy: !smart
      high_odds:
      - low_threshold: 90.0
        high_threshold: 10.0
        high_odds_attempt_rate: 1.0
        high_odds_points:
          max_value: 1000
          percent: 1.0
      - low_threshold: 70.0
        high_threshold: 30.0
        high_odds_attempt_rate: 3.0
        high_odds_points:
          max_value: 5000
          percent: 5.0
      default:
        max_percentage: 55.0
        min_percentage: 45.0
        points:
          max_value: 100000
          percent: 25.0
    filters:
    - !DelayPercentage 50.0
