[package]
name = "twitch-points-miner"
version = "0.1.12"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
indexmap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
twitch_api = { workspace = true, features = ["tpm", "utoipa"] }
clap = { version = "4.5", features = ["derive", "std", "help"], default-features = false }
eyre.workspace = true
rand.workspace = true
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
axum.workspace = true
libsqlite3-sys = { version = "0.29", features = ["bundled"], default-features = false }
diesel = { version = "2", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "2", features = ["sqlite"] }
thiserror = "2"
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9", features = ["axum", "reqwest"] }
tower-http = { workspace = true, features = ["trace", "cors", "fs"] }
tracing-appender = "0.2"
flume.workspace = true
common = { path = "../common", features = ["web_api"] }
http.workspace = true
ansi-to-html = "0.2"
validator.workspace = true

[dev-dependencies]
common = { path = "../common", features = ["web_api", "testing"] }
rstest.workspace = true
reqwest.workspace = true

[[bin]]
name = "twitch-points-miner"
path = "src/main.rs"

# [[bin]]
# name = "default-config"
# path = "src/default_config.rs"
