name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Build web_api
      run: cargo build --features web_api
    - name: Build web_api,analytics
      run: cargo build --features web_api,analytics
    - name: Build analytics
      run: cargo build --features analytics
    - name: Run tests
      run: cargo test
